version = 0.1

[default.deploy.parameters]
stack_name = "cats-and-dogs-api"
resolve_s3 = true
s3_prefix = "cats-and-dogs-api"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
