AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Express API on Lambda via AWS SAM

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    MemorySize: 512

Resources:
  ExpressApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/lambda.handler  # 👈 updated
      CodeUri: .
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          NODE_ENV: production

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
