name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Zip deployment package (including Dockerfile)
        run: |
          zip -r app.zip . -x "**/node_modules/*" "**/.git/*" "**/.github/*" "**/AWSCLIV2.pkg"

      - name: Debug: Show what's in app.zip
        run: unzip -l app.zip

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: cats-and-dogs-api
          environment_name: cats-and-dogs-api-env
          version_label: app-${{ github.run_id }}
          region: ap-southeast-2
          deployment_package: app.zip
