name: Deploy Frontend

on:
  workflow_dispatch:
  push:
    branches: [ dev, master ]
    paths:
      - 'cats-and-dogs-ui/**'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./cats-and-dogs-ui
        run: npm ci

      - name: Build frontend
        working-directory: ./cats-and-dogs-ui
        run: npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync ./cats-and-dogs-ui/dist s3://cats-and-dogs-ui --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2
