name: Deploy Backend

on:
  push:
    branches: [ dev, master ]
    paths:
      - 'cats_and_dogs_api/**'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./cats_and_dogs_api
        run: npm ci

      - name: Build backend
        working-directory: ./cats_and_dogs_api
        run: npm run build

      - name: Install AWS SAM CLI
        run: |
          pip install --user aws-sam-cli

      - name: Build SAM application
        working-directory: ./cats_and_dogs_api
        run: sam build

      - name: Deploy SAM application
        working-directory: ./cats_and_dogs_api
        run: sam deploy --no-confirm-changeset --stack-name cats-and-dogs-api --region ap-southeast-2 --capabilities CAPABILITY_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2
