name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Install EB CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install --upgrade --user awsebcli
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Deploy to Elastic Beanstalk
      run: |
        zip -r deploy.zip . -x '*.git*' '*.github*' 'node_modules/*' 'tests/*' 'dist/*'
        eb init cats-and-dogs-api --region ap-southeast-2 --platform "Docker running on 64bit Amazon Linux 2023"
        eb use cats-and-dogs-api-env
        eb deploy
