name: Deploy React Frontend to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: cats-and-dogs-ui

      - name: Build project
        run: npm run build
        working-directory: cats-and-dogs-ui

      - name: Debug directory contents
        run: ls -la dist
        working-directory: cats-and-dogs-ui

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: cats-and-dogs-ui/dist
